const products= [
    {
        id: 2001,
        name: "Bluetooth Speaker",
        price: 2499,
        category: "Electronics",
        brand: "JBL",
        rating: 4.5,
        stock: 12,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/speaker.webp",
        description: "Portable wireless speaker with deep bass."
    },
    {
        id: 2002,
        name: "Smart TV",
        price: 32999,
        category: "Electronics",
        brand: "Samsung",
        rating: 4.7,
        stock: 5,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/tv.webp",
        description: "43-inch 4K Ultra HD Smart TV."
    },
    {
        id: 2003,
        name: "Running Shoes",
        price: 3999,
        category: "Footwear",
        brand: "Nike",
        rating: 4.4,
        stock: 20,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/shoes.webp",
        description: "Lightweight running shoes for daily training."
    },
    {
        id: 2004,
        name: "Gaming Mouse",
        price: 1799,
        category: "Accessories",
        brand: "Logitech",
        rating: 4.6,
        stock: 15,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/mouse.webp",
        description: "RGB gaming mouse with adjustable DPI."
    },
    {
        id: 2005,
        name: "Mechanical Keyboard",
        price: 4599,
        category: "Accessories",
        brand: "Redragon",
        rating: 4.3,
        stock: 10,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/keyboard.webp",
        description: "Mechanical keyboard with blue switches."
    },
    {
        id: 2006,
        name: "Wireless Earbuds",
        price: 2999,
        category: "Electronics",
        brand: "Boat",
        rating: 4.2,
        stock: 18,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/earbuds.webp",
        description: "True wireless earbuds with noise cancellation."
    },
    {
        id: 2007,
        name: "Laptop Backpack",
        price: 1499,
        category: "Bags",
        brand: "Skybags",
        rating: 4.1,
        stock: 25,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/backpack.webp",
        description: "Water-resistant backpack with laptop compartment."
    },
    {
        id: 2008,
        name: "Fitness Band",
        price: 2199,
        category: "Wearables",
        brand: "Xiaomi",
        rating: 4.0,
        stock: 14,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/band.webp",
        description: "Fitness tracker with heart rate monitoring."
    },
    {
        id: 2009,
        name: "Office Chair",
        price: 8999,
        category: "Furniture",
        brand: "Green Soul",
        rating: 4.5,
        stock: 7,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/chair.webp",
        description: "Ergonomic office chair with lumbar support."
    },
    {
        id: 2010,
        name: "Smartphone",
        price: 24999,
        category: "Electronics",
        brand: "OnePlus",
        rating: 4.6,
        stock: 9,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/phone.webp",
        description: "5G smartphone with AMOLED display."
    },
    {
        id: 2011,
        name: "Coffee Maker",
        price: 3499,
        category: "Home Appliances",
        brand: "Philips",
        rating: 4.2,
        stock: 6,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/coffee.webp",
        description: "Automatic coffee maker for home use."
    },
    {
        id: 2012,
        name: "Gaming Monitor",
        price: 15999,
        category: "Electronics",
        brand: "LG",
        rating: 4.7,
        stock: 4,
        delivery: 1,
        image: "http://localhost:5000/api/uploads/monitor.webp",
        description: "27-inch 144Hz gaming monitor."
    },
];

module.exports=products;
